site_name: CCnocc Blog
site_url: https://zjuccnocc.github.io/
site_author: 吴梓聪(CCnocc)

nav:
  - Home:
    - Hello World!: index.md
    - 关于蒟蒻: Home/about.md
    - 强大的友友们: Home/friend.md
  - CS Course:
    - ./CS Course/index.md
    - 计算机科学基础（B）:
      - CS Course/DJJ/index.md
      - python学习笔记: CS Course/DJJ/python学习笔记.md
      - 大学计算机基础易错点清单: CS Course/DJJ/大学计算机基础易错点清单.md
    - 信息安全原理与数理基础:
      - ./CS Course/XAY/index.md
      - 概率论与数理统计部分:
        - 学术词汇翻译: CS Course/XAY/GT/0翻译.md
        - 概率论基础: CS Course/XAY/GT/1概率论基础.md
        - 随机变量的基本性质: CS Course/XAY/GT/随机变量的性质.md
        - 概率函数梳理: CS Course/XAY/GT/2概率函数梳理.md
        - 各种各样的分布: CS Course/XAY/GT/分布.md
        - 马尔可夫不等式和切比雪夫不等式: CS Course/XAY/GT/3不等式.md
        - 大数定理: CS Course/XAY/GT/4大数定律.md
        - 估计: CS Course/XAY/GT/估计.md
        - 假设检验: CS Course/XAY/GT/假设检验.md
        - 概率论与数理统计历年题: CS Course/XAY/GT/来点实践.md
        - 中心极限定理: CS Course/XAY/GT/中心极限定理.md
    - 计算机系统:
      - CS Course/SYS/index.md
      - 计算机系统Ⅰ:
        - 实验部分:
          - Lab0-1: CS Course/SYS/SYS1/LAB/Lab0-1实验报告.md
          - Lab0-2: CS Course/SYS/SYS1/LAB/Lab0-2实验报告.md
          - Lab1: CS Course/SYS/SYS1/LAB/Lab1实验报告.md
          - Lab2: CS Course/SYS/SYS1/LAB/Lab2实验报告.md
          - Lab3: CS Course/SYS/SYS1/LAB/Lab3实验报告.md
          - Lab4-1: CS Course/SYS/SYS1/LAB/Lab4-1实验报告.md
          - Lab4-2: CS Course/SYS/SYS1/LAB/Lab4-2实验报告.md
          - Lab5: CS Course/SYS/SYS1/LAB/Lab5实验报告.md
      - 计算机系统Ⅱ:
        - 实验部分:
          - Lab0: ./CS Course/SYS/SYS2/LAB/Lab0/Lab5实验报告.md
          - Lab1: ./CS Course/SYS/SYS2/LAB/Lab1/Lab1 Pipeline.md
          - Lab2: ./CS Course/SYS/SYS2/LAB/Lab2/Lab2 Forwarding 及 AXI4-lite 总线内存模型.md
          - Lab3: ./CS Course/SYS/SYS2/LAB/Lab3/Lab3：RV64内核引导实验报告.md
          - Lab4: ./CS Course/SYS/SYS2/LAB/Lab4/Lab4 RV64 下的时钟中断处理.md
          - Lab5: ./CS Course/SYS/SYS2/LAB/Lab5/Lab5：RV64 内核线程调度.md
          - Lab6: ./CS Course/SYS/SYS2/LAB/Lab6/Lab6：综合实验.md
    - Machine Learning:
      - ./CS Course/Machine Learning/index.md
      - P1 Welcome: CS Course/Machine Learning/attachments/斯坦福229：机器学习【P1 Welcome】.md
      - P2 Liner Regression & Gradient Descent: CS Course/Machine Learning/attachments/斯坦福229：机器学习【P2 Liner Regression & Gradient Descent】.md
      - P3 Locally Weighted & Logiscal Regression: CS Course/Machine Learning/attachments/斯坦福229：机器学习【P3 Locally Weighted & Logiscal Regression】.md
    - 技术沟通:
      - CS Course/TC/index.md
      - 个人作业:
        - 个人作业：文献综述: CS Course/TC/attachments/个人作业：文献综述.md
        - 个人作业：修改意见-1: CS Course/TC/attachments/个人作业：修改意见-1.md
        - 个人作业：修改意见-2: CS Course/TC/attachments/个人作业：修改意见-2.md
      - 小组讨论:
        - 小组讨论1：论文英文特点: CS Course/TC/attachments/小组讨论1：论文英文特点.md
        - 小组讨论2：论文阅读报告: CS Course/TC/attachments/小组讨论2：论文阅读报告.md
        - 小组讨论3：论文深入阅读: CS Course/TC/attachments/小组讨论3：论文深入阅读.md
        - 小组讨论4：探究性写作联系: CS Course/TC/attachments/小组讨论4：探究性写作联系.md
        - 小组讨论5：评价文献综述: CS Course/TC/attachments/小组讨论5：评价文献综述.md
        - 小组讨论6：撰写摘要: CS Course/TC/attachments/小组讨论6：撰写摘要.md
        - 小组讨论7：评价开题报告: CS Course/TC/attachments/小组讨论7：评价开题报告.md
        - 小组讨论8：评价毕业论文: CS Course/TC/attachments/小组讨论8：评价毕业论文.md
        - 小组讨论9：可行性分析: CS Course/TC/attachments/小组讨论9：可行性分析.md
        - 小组讨论10：本科毕业论文实例分析: CS Course/TC/attachments/小组讨论10：本科毕业论文实例分析.md
        - 小组讨论11：幻灯片问题: CS Course/TC/attachments/小组讨论11：幻灯片问题.md
        - 小组讨论12：图片搜索: CS Course/TC/attachments/小组讨论12：图片搜索.md
        - 小组讨论13：图库搜索: CS Course/TC/attachments/小组讨论13：图库搜索.md
        - 小组讨论14：分析演讲的问题: CS Course/TC/attachments/小组讨论14：分析演讲的问题.md
      - 小组作业:
        - 小组作业2：论文阅读: CS Course/TC/attachments/小组作业2：论文阅读.md
  - General Course:
      - ./General Course/index.md
      - 大学英语:
        - General Course/ENG/index.md
        - 作文:
          - Childhood Memories: General Course/ENG/大学英语作文-Childhood-Memories.md
          - My Winter Break: General Course/ENG/大学英语作文-My-Winter-Break.md
          - To Make Preparations for the Future Job Market: General Course/ENG/大学英语作文-To Make Preparations for the Future Job Market.md
        - 读书笔记:
          - 在彼处: General Course/ENG/读书笔记-在彼处.md
          - Never Judge One Only by Academic Success: General Course/ENG/读书笔记-Never Judge One Only by Academic Success.md
        - Pre资料: General Course/ENG/Pre/index.md
      - 大学物理实验:
        - General Course/DXWLSY/index.md
        - 等厚干涉: General Course/DXWLSY/等厚干涉.md
        - 分光计: General Course/DXWLSY/分光计.md
        - 光速的测定: General Course/DXWLSY/光速的测定.md
        - 空气密度测定: General Course/DXWLSY/空气密度测定实验数据处理.md
        - 密里根油滴实验: General Course/DXWLSY/密里根油滴实验数据处理.md
        - 碰撞试验: General Course/DXWLSY/碰撞试验.md
        - 声速的测定: General Course/DXWLSY/声速的测定.md
        - 杨氏模量实验: General Course/DXWLSY/杨氏模量实验.md
        - 整流器实验: General Course/DXWLSY/整流器实验.md
        - 组装万用表: General Course/DXWLSY/组装万用表.md
      - 数码摄影基础:
        - General Course/SMSYJC/index.md
        - 作品赏析:
          - 第一次摄影作品: General Course/SMSYJC/《数码摄影基础》第一次摄影作品.md
          - 拍摄照片赏析: General Course/SMSYJC/《数码摄影基础》拍摄照片赏析.md
          - 摄影作品赏析: General Course/SMSYJC/《数码摄影基础》摄影作品赏析.md
        - 实验报告:
          - 数码摄影基础-实验报告1: General Course/SMSYJC/《数码摄影基础》实验报告.md
          - 数码摄影基础-实验报告2: General Course/SMSYJC/实验报告.md
      - 中国近现代史纲要:
        - General Course/ZGJXDSGY/index.md
        - 论文《代际鸿沟与交流失位》: General Course/ZGJXDSGY/《中国近现代史纲要》代际鸿沟与交流失位.md
        - 展示资料《珍宝岛守卫战》: General Course/ZGJXDSGY/大致过程.md
      - 中国改革开放史:
        - General Course/ZGGGKFS/index.md
        - 当代中国的对外贸易、汇率和FDI体制改革历程: General Course/ZGGGKFS/当代中国的对外贸易、汇率和FDI体制改革历程.md
        - 中国改革开放史思考题: General Course/ZGGGKFS/中国改革开放史思考题.md
      - 微积分(甲)Ⅰ&Ⅱ: General Course/VJF/index.md
      - 生物进化与设计:
        - General Course/SWJHDL/index.md
        - 枕头的进化与发展: General Course/SWJHDL/枕头的进化与发展.md
      - 军事理论:
        - General Course/JSLL/index.md
        - 中国与邻国的南海争端问题与可行解决方案: General Course/JSLL/中国与邻国的南海争端问题与可行解决方案.md
      - 古典与流行音乐鉴赏:
        - General Course/GDYLXYYJS/index.md
        - 周杰伦作品中的元素融合与借鉴: General Course/GDYLXYYJS/周杰伦作品中的元素融合与借鉴.md
        - 音乐会观后感: General Course/GDYLXYYJS/观民乐团音乐会有感.md
        - 听音配文: General Course/GDYLXYYJS/听音配文Music 2.md
      - 博弈论基础:
        - General Course/BYL/index.md
        - 弈论模型汇总与整理: General Course/BYL/弈论模型汇总与整理.md
        - 游戏参与和总结: General Course/BYL/游戏参与和总结.md
  - Blog Writeup: 
      - ./BlogWriteup/index.md
      - Mkdocs+GithubPages: ./BlogWriteup/Mkdocs使用Writeup.md
      - Hexo+服务器: ./BlogWriteup/Hexo使用指南.md
  - Major Relative:
    - Major Relative/index.md
    - 转专业经验帖: Major Relative/转专业经验帖.md
    - 金融专业确认交流情况: Major Relative/金融专业确认交流情况.md
    - 信息安全专业确认交流情况: Major Relative/信息安全专业确认交流情况.md
    - 信息安全专业确认交流情况-二: Major Relative/信息安全专业确认交流情况-二.md
    

theme: 
  name: material
  language: zh    
  features:  #导航
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes # 次级索引页，直接将文档附加到章节，提供概览页面，在相应文件夹中创建index.md添加到导航nav开头。不兼容toc.integrate。
    - toc.follow   #锚跟随，文章小标题目录侧边栏自动滚动，以便活动锚点始终可见（付费功能）
    - search.highlight  #搜索词高亮突出显示
    - search.share   #搜索共享
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    - content.tabs.link # 链接标签
    - navigation.footer # 底部导航栏
    - navigation.path # 导航路径， 目前好像没啥用
    - navigation.prune # 只构建可见的页面
    - navigation.tabs # 顶级索引被作为tab
  palette:
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
  favicon: img/favicon.ico
  icon: # 一些用到的icon
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZJUCCnocc/

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
      permalink_title: 点击此处可置顶内容
  - meta
  - tables # 启用Markdown表格语法。
  - def_list #支持定义列表的创建。
  - attr_list #允许在Markdown元素上添加HTML属性。
  - md_in_html #允许在HTML块内使用Markdown语法。
  - sane_lists
  - admonition #支持创建带有标题的特殊块，用于提示、注意事项等。
  - pymdownx.keys #支持键盘按键的表示。
  - pymdownx.mark #支持高亮标记文本。
  - pymdownx.tilde # 支持删除线和下划线文本。
  - pymdownx.caret  #添加对插入文本和删除文本的支持。
  - pymdownx.critic
  - pymdownx.details # 支持创建可折叠的详情块（HTML <details> 和 <summary> 标签）。
  - pymdownx.betterem #改进了强调（斜体和粗体）的解析。
  - pymdownx.snippets #允许自动包含其他Markdown文件的内容。
  - pymdownx.magiclink
  - pymdownx.smartsymbols #自动将某些文本模式转换为符号，如箭头和数学符号。
  - pymdownx.inlinehilite #允许在文本中直接高亮代码片段。
  - pymdownx.tabbed: #
      alternate_style: true
  - pymdownx.emoji: #通过名称或代码添加表情符号，支持自定义表情生成器。
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed: #允许创建标签页，用于在同一位置显示不同的内容块。
      alternate_style: true 
  - pymdownx.tasklist:  #支持任务列表，允许使用自定义复选框。 
      custom_checkbox: true
  - pymdownx.highlight: #改进代码高亮显示，支持行号、行跨度等特性。
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences: #提供更强大的代码块功能，支持自定义围栏（fences）和Mermaid图表。
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:  #提供对数学表达式的支持，允许在Markdown中直接使用LaTeX语法。
      generic: true
  - markdown.extensions.sane_lists #有序无序列表的一个扩展。
  - markdown.extensions.wikilinks #支持wiki链接

repo_name: ZJUCCnoccBlogSource # 仓库名称
repo_url: https://github.com/ZJUccnocc/ZJUccnocc.github.io # 仓库地址


plugins:
  - search

#### most of these are modified form grate Tonycrane ! ####
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/counter.css
  - assets/stylesheets/custom.css
  - assets/stylesheets/glightbox.min.css
  - assets/stylesheets/galaxy.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css


extra_javascript:
  - assets/javascripts/katex.js 
  - assets/javascripts/mathjax.js
  - assets/javascripts/fireworks.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/glightbox.min.js
