site_name: CCnocc's Blog
site_url: https://zjuccnocc.github.io/
site_author: ccnocc
nav:
  - Home:
    - index.md
    - about: "./Home/about.md"
    - friend: "./Home/friend.md"
  - CS Course:
    - ./CS Course/index.md
    - 大学计算机基础:
      - python学习笔记: "./CS Course/大学计算机基础（已绝版）/python学习笔记.md"
      - 大学计算机基础易错点清单: "./CS Course/大学计算机基础（已绝版）/大学计算机基础易错点清单.md"
    - 计算机系统:
      # - 计算机系统Ⅰ:
      #     - 实验部分:
      #         - Lab1: 
      #         - Lab2: 
      - 计算机系统Ⅱ:
        - 实验部分:
          - Lab0: "./CS Course/计算机系统/计算机系统2/实验部分/Lab0/Lab5实验报告.md"
  - General Course:
      - ./General Course/index.md
      - 大学英语:
        - 作文:
          - Childhood Memories: "./General Course/大学英语/大学英语作文-Childhood-Memories.md"
          - My Winter Break: "./General Course/大学英语/大学英语作文-My-Winter-Break.md"
        - 读书笔记:
          - 在彼处: "./General Course/大学英语/读书笔记-在彼处.md"
      - 数码摄影基础:
        - 作品赏析:
          - 第一次摄影作品: "./General Course/数码摄影基础/《数码摄影基础》第一次摄影作品.md"
          - 拍摄照片赏析: "./General Course/数码摄影基础/《数码摄影基础》拍摄照片赏析.md"
          - 摄影作品赏析: "./General Course/数码摄影基础/《数码摄影基础》摄影作品赏析.md"
        - 实验报告:
          - 数码摄影基础-实验报告: "./General Course/数码摄影基础/《数码摄影基础》实验报告.md"
      - 中国近现代史纲要:
        - 论文《代际鸿沟与交流失位》: "./General Course/中国近代史纲要/《中国近现代史纲要》代际鸿沟与交流失位.md"
        - 展示资料《珍宝岛守卫战》: "./General Course/中国近代史纲要/大致过程.md"
  - Blog Writeup: 
      - "./BlogWriteup/Mkdocs使用Writeup.md"
      - "./BlogWriteup/Hexo使用指南.md"

 


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - mdx_truly_sane_lists
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
repo_name: ZJUCCnoccBlogSource # 仓库名称
repo_url: https://github.com/ZJUCCnocc/BlogCode.git/ # 仓库地址
theme:
  name: material
  features: # 功能
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    - navigation.tabs # 顶级索引被作为tab
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - toc.follow # 目录跟踪-页面右侧的小目录
  font: false
  palette:
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  favicon: img/favicon.ico # 网站图标 似乎不需要管
  icon: # 一些用到的icon
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code
extra_css:
  - css/custom.css
